// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/fileupload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_fileupload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileupload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_fileupload_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileChunk) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileChunk) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StoredPath    string                 `protobuf:"bytes,3,opt,name=stored_path,json=storedPath,proto3" json:"stored_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_proto_fileupload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileupload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_proto_fileupload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadStatus) GetStoredPath() string {
	if x != nil {
		return x.StoredPath
	}
	return ""
}

type GetChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunksRequest) Reset() {
	*x = GetChunksRequest{}
	mi := &file_proto_fileupload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunksRequest) ProtoMessage() {}

func (x *GetChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileupload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunksRequest.ProtoReflect.Descriptor instead.
func (*GetChunksRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileupload_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunksRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetChunksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadedChunks []int64                `protobuf:"varint,1,rep,packed,name=uploaded_chunks,json=uploadedChunks,proto3" json:"uploaded_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChunksResponse) Reset() {
	*x = GetChunksResponse{}
	mi := &file_proto_fileupload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunksResponse) ProtoMessage() {}

func (x *GetChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileupload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunksResponse.ProtoReflect.Descriptor instead.
func (*GetChunksResponse) Descriptor() ([]byte, []int) {
	return file_proto_fileupload_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunksResponse) GetUploadedChunks() []int64 {
	if x != nil {
		return x.UploadedChunks
	}
	return nil
}

var File_proto_fileupload_proto protoreflect.FileDescriptor

const file_proto_fileupload_proto_rawDesc = "" +
	"\n" +
	"\x16proto/fileupload.proto\x12\x02pb\"\xb8\x01\n" +
	"\tFileChunk\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x03R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\"c\n" +
	"\fUploadStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstored_path\x18\x03 \x01(\tR\n" +
	"storedPath\"+\n" +
	"\x10GetChunksRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"<\n" +
	"\x11GetChunksResponse\x12'\n" +
	"\x0fuploaded_chunks\x18\x01 \x03(\x03R\x0euploadedChunks2\x86\x01\n" +
	"\x11FileUploadService\x12/\n" +
	"\n" +
	"UploadFile\x12\r.pb.FileChunk\x1a\x10.pb.UploadStatus(\x01\x12@\n" +
	"\x11GetUploadedChunks\x12\x14.pb.GetChunksRequest\x1a\x15.pb.GetChunksResponseB8Z6github.com/siddheshRajendraNimbalkar/upload-backend/pbb\x06proto3"

var (
	file_proto_fileupload_proto_rawDescOnce sync.Once
	file_proto_fileupload_proto_rawDescData []byte
)

func file_proto_fileupload_proto_rawDescGZIP() []byte {
	file_proto_fileupload_proto_rawDescOnce.Do(func() {
		file_proto_fileupload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fileupload_proto_rawDesc), len(file_proto_fileupload_proto_rawDesc)))
	})
	return file_proto_fileupload_proto_rawDescData
}

var file_proto_fileupload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fileupload_proto_goTypes = []any{
	(*FileChunk)(nil),         // 0: pb.FileChunk
	(*UploadStatus)(nil),      // 1: pb.UploadStatus
	(*GetChunksRequest)(nil),  // 2: pb.GetChunksRequest
	(*GetChunksResponse)(nil), // 3: pb.GetChunksResponse
}
var file_proto_fileupload_proto_depIdxs = []int32{
	0, // 0: pb.FileUploadService.UploadFile:input_type -> pb.FileChunk
	2, // 1: pb.FileUploadService.GetUploadedChunks:input_type -> pb.GetChunksRequest
	1, // 2: pb.FileUploadService.UploadFile:output_type -> pb.UploadStatus
	3, // 3: pb.FileUploadService.GetUploadedChunks:output_type -> pb.GetChunksResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fileupload_proto_init() }
func file_proto_fileupload_proto_init() {
	if File_proto_fileupload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fileupload_proto_rawDesc), len(file_proto_fileupload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fileupload_proto_goTypes,
		DependencyIndexes: file_proto_fileupload_proto_depIdxs,
		MessageInfos:      file_proto_fileupload_proto_msgTypes,
	}.Build()
	File_proto_fileupload_proto = out.File
	file_proto_fileupload_proto_goTypes = nil
	file_proto_fileupload_proto_depIdxs = nil
}
